(()=>{'use strict';
const $=id=>document.getElementById(id), SW=1672, SH=941, HEROES=['Vexa','Miko','Tali','Runo','Zako','Eren'];
const SAVEKEY='level_master_z1_clean_v1';
let save=load(), selected=save.hero||0, G=null, last=0, paused=false, soundOn=true;
const keys={left:false,right:false,jump:false};
function load(){try{return JSON.parse(localStorage.getItem(SAVEKEY))||{name:'',hero:0,current:1,worlds:{}}}catch(e){return{name:'',hero:0,current:1,worlds:{}}}}
function persist(){localStorage.setItem(SAVEKEY,JSON.stringify(save))}
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active')}
function fit(){const s=Math.min(innerWidth/SW,innerHeight/SH);$('stage').style.transform=`scale(${s})`}
addEventListener('resize',fit);fit();
// preload
const assets=['assets/ui/home.webp','assets/ui/heroes.webp','assets/ui/zone.webp'];let done=0;assets.forEach(src=>{const im=new Image();im.onload=im.onerror=()=>{$('bootBar').style.width=`${(++done/assets.length)*100}%`;if(done===assets.length)setTimeout(()=>{$('boot').style.display='none'},150)};im.src=src});
// home
$('nameInput').value=save.name||'';$('startBtn').onclick=()=>{save.name=$('nameInput').value.trim()||'Jugador';persist();buildHeroes();show('heroes')};$('continueBtn').onclick=()=>{save.name=$('nameInput').value.trim()||save.name||'Jugador';persist();buildMap();show('zone')};
function buildHeroes(){const g=$('heroGrid');g.innerHTML='';HEROES.forEach((h,i)=>{const b=document.createElement('button');b.className='heroChoice'+(i===selected?' selected':'');b.setAttribute('aria-label',h);b.onclick=()=>{selected=i;buildHeroes()};g.appendChild(b)})}
$('heroConfirm').onclick=()=>{save.hero=selected;persist();buildMap();show('zone')};$('heroBack').onclick=()=>show('home');
function worldState(w){return save.worlds[w]||{done:false,star:0,coins:0,best:0}}
function buildMap(){const grid=$('worldGrid');grid.innerHTML='';$('playerLabel').textContent=save.name||'Jugador';let tc=0,ts=0;Object.values(save.worlds).forEach(v=>{tc+=v.coins||0;ts+=v.star||0});$('totalCoins').textContent=tc;$('totalStars').textContent=`${ts}/20`;const cur=Math.max(1,save.current||1);$('chapterLabel').textContent=LM_LEVELS.chapterFor(cur).label;for(let w=1;w<=20;w++){const st=worldState(w),b=document.createElement('button'),locked=w>cur;b.className='worldBtn'+(locked?' locked':st.done?' done':w===cur?' current':'');b.innerHTML=`${w}<small>${LM_LEVELS.names[w-1]}</small>${st.done?`<em>★${st.star}</em>`:''}`;b.disabled=locked;b.onclick=()=>startWorld(w);grid.appendChild(b)}}$('zoneBack').onclick=()=>show('home');
// controls
const GAMECODES=new Set(['ArrowLeft','ArrowRight','ArrowUp','KeyA','KeyD','KeyW']);function keyEvent(e,v){if(e.code==='ArrowLeft'||e.code==='KeyA')keys.left=v;if(e.code==='ArrowRight'||e.code==='KeyD')keys.right=v;if(e.code==='ArrowUp'||e.code==='KeyW')keys.jump=v;if(GAMECODES.has(e.code))e.preventDefault()}addEventListener('keydown',e=>keyEvent(e,true),{passive:false});addEventListener('keyup',e=>keyEvent(e,false),{passive:false});addEventListener('blur',()=>Object.keys(keys).forEach(k=>keys[k]=false));document.querySelectorAll('#touchControls button').forEach(b=>{const k=b.dataset.key;b.onpointerdown=e=>{e.preventDefault();keys[k]=true};['onpointerup','onpointercancel','onpointerleave'].forEach(ev=>b[ev]=e=>{e.preventDefault();keys[k]=false})});
// audio
function beep(type){if(!soundOn)return;try{const A=window.AudioContext||window.webkitAudioContext,a=window._lmAudio||(window._lmAudio=new A()),o=a.createOscillator(),g=a.createGain(),t=a.currentTime,map={coin:[760,.05],star:[980,.12],jump:[410,.04],hit:[140,.10],win:[680,.2],key:[900,.08],bounce:[520,.06]};const q=map[type]||[450,.05];o.type='square';o.frequency.setValueAtTime(q[0],t);if(type==='win')o.frequency.exponentialRampToValueAtTime(1200,t+.18);g.gain.setValueAtTime(.045,t);g.gain.exponentialRampToValueAtTime(.001,t+q[1]);o.connect(g);g.connect(a.destination);o.start();o.stop(t+q[1])}catch(e){}}
$('soundBtn').onclick=()=>{soundOn=!soundOn;$('soundBtn').textContent=soundOn?'🔊':'🔇'};$('pauseBtn').onclick=()=>{paused=!paused;$('pauseBtn').textContent=paused?'▶':'⏸'};
// game generation
const cv=$('gameCanvas'),ctx=cv.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=false;const GRAV=2250,SPEED=425,JUMP=-830;
function rng(n){const x=Math.sin(n*999.91)*43758.5453;return x-Math.floor(x)}
function makeLevel(spec){const gy=742,plats=[{x:0,y:gy,w:760,h:260,type:'ground'}],dyn=[],zones=[],items=[],enemies=[],decor=[];let x=700,seed=spec.world*811;
 const pieces=12+spec.difficulty*2;for(let i=0;i<pieces;i++){let gap=80+rng(seed+i)*92+spec.difficulty*10,pw=310+rng(seed+i+20)*360,raise=(rng(seed+i+40)>.68?70:0);x+=gap;plats.push({x,y:gy-raise,w:pw,h:300,type:'ground'});x+=pw}
 // ensure final runway
 plats.push({x:spec.length-1600,y:gy,w:1450,h:300,type:'ground'});
 const m=spec.mechanics;
 if(m.includes('mover'))for(let i=0;i<2+Math.floor(spec.difficulty/2);i++)dyn.push({type:'move',x:1300+i*1500,y:gy-170-(i%2)*70,w:170,h:28,base:1300+i*1500,amp:110+spec.difficulty*20,speed:.65+i*.11});
 if(m.includes('lift'))for(let i=0;i<2;i++)dyn.push({type:'lift',x:2200+i*2100,y:gy-110,w:160,h:28,baseY:gy-110,amp:130,speed:.7+i*.12});
 if(m.includes('crumble'))for(let i=0;i<3;i++)dyn.push({type:'crumble',x:1800+i*1350,y:gy-120,w:145,h:28,fall:false,vy:0,touched:0});
 if(m.includes('ghost'))for(let i=0;i<3;i++)dyn.push({type:'ghost',x:1600+i*1550,y:gy-150-(i%2)*55,w:160,h:28,phase:i*.8});
 if(m.includes('bounce'))for(let i=0;i<3;i++)items.push({type:'bounce',x:1250+i*1700,y:gy-22,w:76,h:22});
 if(m.includes('wind'))zones.push({type:'wind',x:2200,y:0,w:900,h:gy,dir:1},{type:'wind',x:4400,y:0,w:700,h:gy,dir:-1});
 if(m.includes('door'))items.push({type:'door',x:spec.length-1180,y:gy-145,w:60,h:145,open:false});
 if(m.includes('key'))items.push({type:'key',x:spec.length-2400,y:gy-115,w:52,h:52,taken:false,id:'door'});
 for(let i=0;i<spec.coins;i++)items.push({type:'coin',x:520+i*(spec.length-1000)/(spec.coins-1),y:gy-105-(i%5===2?75:0),taken:false});
 items.push({type:'star',x:spec.length*.62,y:gy-245,w:50,h:50,taken:false});
 const jumpers=Math.min(6,1+Math.floor(spec.world/4)),flyers=spec.world<3?0:Math.min(5,Math.floor(spec.world/5)+1);for(let i=0;i<jumpers;i++)enemies.push({type:'jumper',x:1450+i*1250,y:gy-54,w:54,h:54,base:1450+i*1250,t:rng(seed+i)*4});for(let i=0;i<flyers;i++)enemies.push({type:'flyer',x:2100+i*1450,y:gy-245,w:65,h:43,base:2100+i*1450,t:rng(seed+i+60)*4});
 let boss=null;if(spec.boss){boss={x:spec.length-760,y:gy-168,w:174,h:168,t:0,keys:[{x:spec.length-3300,y:gy-90,w:58,h:58,taken:false},{x:spec.length-2450,y:gy-165,w:58,h:58,taken:false},{x:spec.length-1650,y:gy-90,w:58,h:58,taken:false}]};}
 return{spec,gy,plats,dyn,zones,items,enemies,boss,portal:{x:spec.length-270,y:gy-150,w:96,h:150},length:spec.length}}
function startWorld(w){const spec=LM_LEVELS.make(w);G={world:w,L:makeLevel(spec),p:{x:140,y:440,w:54,h:72,vx:0,vy:0,on:false},camera:0,score:0,coins:0,star:0,dead:false,finished:false};paused=false;Object.keys(keys).forEach(k=>keys[k]=false);$('nameInput').blur();show('game');updateHud();$('missionCard').classList.remove('hiddenSoft');$('missionTitle').textContent=`MUNDO ${w} · ${spec.name}`;$('missionText').textContent=mission(spec);setTimeout(()=>$('missionCard').classList.add('hiddenSoft'),w===20?4200:2200);last=performance.now();requestAnimationFrame(loop)}
function mission(s){if(s.world===20)return'Reuní las 3 Llaves Master. Con 3/3 el monstruo se apartará y el portal se abrirá.';const m=s.mechanics;if(m.includes('door'))return'Encontrá la llave para abrir la puerta del camino.';if(m.includes('wind'))return'Las corrientes de aire empujan: usalas a tu favor.';if(m.includes('bounce'))return'Los trampolines amarillos te lanzan más alto.';if(m.includes('ghost'))return'Algunas plataformas aparecen y desaparecen.';if(m.includes('crumble'))return'Algunas plataformas caen después de pisarlas.';return'Buscá la estrella y llegá al Portal Master.'}
function updateHud(){const b=G.L.boss,k=b?b.keys.filter(x=>x.taken).length:0;$('hudPlayer').textContent=`${save.name||'Jugador'} · ${HEROES[save.hero||0]}`;$('hudWorld').textContent=`ZONA 1 · MUNDO ${G.world}`;$('hudStats').textContent=G.world===20?`🪙 ${G.coins} · ★ ${G.star} · 🗝 ${k}/3 · ${G.score} pts`:`🪙 ${G.coins} · ★ ${G.star} · ${G.score} pts`;$('hint').textContent=G.world===20?'←/A · →/D · ↑/W · reuní las 3 Llaves Master':'←/A izquierda · →/D derecha · ↑/W saltar'}
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),500)}
function fail(){if(!G||G.dead)return;G.dead=true;beep('hit');toast('¡CASI!');setTimeout(()=>startWorld(G.world),620)}
function finish(){if(G.finished)return;G.finished=true;beep('win');const pts=G.score+100,prev=worldState(G.world),st={done:true,best:Math.max(prev.best||0,pts),star:Math.max(prev.star||0,G.star),coins:Math.max(prev.coins||0,G.coins)};save.worlds[G.world]=st;save.current=G.world<20?Math.max(save.current||1,G.world+1):20;persist();$('resCoins').textContent=G.coins;$('resStar').textContent=G.star?'★':'☆';$('resScore').textContent=pts;$('resultText').textContent=`Mundo ${G.world} · ${LM_LEVELS.names[G.world-1]}`;setTimeout(()=>show(G.world===20?'zoneComplete':'complete'),300)}
$('nextBtn').onclick=()=>startWorld(Math.min(20,G.world+1));$('replayBtn').onclick=()=>startWorld(G.world);$('mapBtn').onclick=()=>{buildMap();show('zone')};$('finalMapBtn').onclick=()=>{buildMap();show('zone')};
function update(dt){const L=G.L,p=G.p;let wind=0;L.zones.forEach(z=>{if(hit(p,z))wind+=z.dir*180});p.vx=(keys.left?-SPEED:0)+(keys.right?SPEED:0)+wind;if(keys.jump&&p.on){p.vy=JUMP;p.on=false;beep('jump')}p.vy+=GRAV*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.on=false;
 L.dyn.forEach((d,i)=>{if(d.type==='move')d.x=d.base+Math.sin(performance.now()/1000*d.speed+i)*d.amp;if(d.type==='lift')d.y=d.baseY+Math.sin(performance.now()/1000*d.speed+i)*d.amp;if(d.type==='crumble'&&d.fall){d.vy+=950*dt;d.y+=d.vy*dt}if(d.type==='ghost')d.visible=Math.sin(performance.now()/900+d.phase)>.05});
 const solids=[...L.plats,...L.dyn.filter(d=>d.type!=='ghost'||d.visible)];solids.forEach(s=>{if(p.vy>=0&&p.x+p.w>s.x&&p.x<s.x+s.w&&p.y+p.h>=s.y&&p.y+p.h<=s.y+38+p.vy*dt){p.y=s.y-p.h;p.vy=0;p.on=true;if(s.type==='crumble'&&!s.fall){s.touched+=dt;if(s.touched>.1){s.fall=true;s.vy=15}}}});
 L.items.forEach(it=>{if(it.type==='coin'&&!it.taken&&near(p,it,45)){it.taken=true;G.coins++;G.score+=10;beep('coin');updateHud()}if(it.type==='star'&&!it.taken&&near(p,it,55)){it.taken=true;G.star=1;G.score+=50;beep('star');updateHud()}if(it.type==='bounce'&&hit(p,it)&&p.vy>=0){p.vy=-1040;p.on=false;beep('bounce')}if(it.type==='key'&&!it.taken&&hit(p,it)){it.taken=true;G.score+=35;beep('key');L.items.filter(x=>x.type==='door').forEach(d=>d.open=true);toast('🗝 LLAVE');updateHud()}});
 L.enemies.forEach((e,i)=>{e.t+=dt;if(e.type==='jumper'){e.x=e.base+Math.sin(e.t*1.5)*(95+L.spec.difficulty*13);e.y=L.gy-e.h-Math.abs(Math.sin(e.t*2.1))*82}else{e.x=e.base+Math.sin(e.t*1.0)*(160+L.spec.difficulty*18);e.y=L.gy-245-(i%2)*55+Math.sin(e.t*2)*48}if(hit(p,e))fail()});
 L.items.filter(x=>x.type==='door'&&!x.open).forEach(d=>{if(hit(p,d)){p.x=d.x-p.w-2;p.vx=0}});
 if(L.boss){const b=L.boss;b.t+=dt;b.keys.forEach((k,i)=>{if(!k.taken&&hit(p,k)){k.taken=true;G.score+=40;beep('key');toast(`🗝 ${b.keys.filter(q=>q.taken).length}/3`);updateHud()}});const all=b.keys.every(k=>k.taken);if(!all){b.x=L.length-760+Math.sin(b.t*.55)*90;if(hit(p,b))fail()}else b.x+=(L.length+280-b.x)*Math.min(1,dt*2.4)}
 const open=(!L.boss||L.boss.keys.every(k=>k.taken))&&!L.items.some(x=>x.type==='door'&&!x.open);if(open&&hit(p,L.portal))finish();if(p.y>SH+160)fail();p.x=Math.max(0,Math.min(L.length-60,p.x));G.camera=Math.max(0,Math.min(L.length-SW,p.x-SW*.31))}
function near(a,b,r){return Math.hypot(a.x+a.w/2-(b.x+b.w/2),a.y+a.h/2-(b.y+b.h/2))<r}
// render
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}
const pals={day:{a:'#0ea7ff',b:'#8bdcff',far:'#5faab1',mid:'#3d815f',grass:'#6bc42d',grass2:'#3b8e1d',dirt:'#98521f',dirt2:'#5b2c17',leaf:'#4dad16',leaf2:'#297b18'},sunset:{a:'#d96669',b:'#ffc36d',far:'#89685a',mid:'#4b6b4b',grass:'#61aa2d',grass2:'#39791e',dirt:'#8b4b26',dirt2:'#532a1c',leaf:'#4c8f23',leaf2:'#2c631c'},night:{a:'#071c43',b:'#153f70',far:'#1b3a53',mid:'#153c3a',grass:'#3c7d2b',grass2:'#265820',dirt:'#5b392c',dirt2:'#34241e',leaf:'#2d6b2c',leaf2:'#1d4a28'},portal:{a:'#061433',b:'#163d67',far:'#243c55',mid:'#1a4441',grass:'#437d2e',grass2:'#285a22',dirt:'#603a2b',dirt2:'#37231e',leaf:'#316c2d',leaf2:'#1e4928'}};
function cloud(x,y,s){rect(x,y+18*s,100*s,25*s,'#effbff');rect(x+18*s,y,43*s,31*s,'#effbff');rect(x+55*s,y+7*s,31*s,27*s,'#d9f4ff')}
function tree(x,y,s,p){rect(x+36*s,y-116*s,30*s,120*s,'#7d421d');rect(x+44*s,y-116*s,8*s,120*s,'#ad6027');[[0,-160,72,50],[35,-184,70,62],[-20,-125,82,56],[56,-121,77,52],[22,-207,57,54]].forEach((b,i)=>{rect(x+b[0]*s,y+b[1]*s,b[2]*s,b[3]*s,i%2?p.leaf:p.leaf2);rect(x+(b[0]+7)*s,y+(b[1]+7)*s,(b[2]-14)*s,8*s,'#79cf35')})}
function background(L){const p=pals[L.spec.env],g=ctx.createLinearGradient(0,0,0,SH);g.addColorStop(0,p.a);g.addColorStop(1,p.b);ctx.fillStyle=g;ctx.fillRect(0,0,SW,SH);if(L.spec.env==='night'||L.spec.env==='portal'){for(let i=0;i<38;i++)rect((i*157)%SW,(i*83)%390,3+(i%2)*2,3+(i%2)*2,'#dff6ffbb');ctx.fillStyle='#e2f2ff';ctx.beginPath();ctx.arc(1360,125,46,0,Math.PI*2);ctx.fill()}else{ctx.fillStyle='#ffd651';ctx.beginPath();ctx.arc(L.spec.env==='sunset'?1280:1370,L.spec.env==='sunset'?155:125,48,0,Math.PI*2);ctx.fill();for(let i=0;i<6;i++)cloud(((i*335-G.camera*.08)%(SW+380))-100,75+(i%3)*78,.8+(i%2)*.2)}for(let i=0;i<10;i++){const x=((i*285-G.camera*.10)%(SW+430))-160,h=140+(i%4)*88;rect(x,620-h,215,h,p.far);for(let yy=620-h;yy<620;yy+=24)for(let xx=x;xx<x+215;xx+=24)if(((xx+yy+i*7)/24|0)%3===0)rect(xx,yy,22,22,'#ffffff0c')}for(let i=0;i<12;i++){const x=((i*240-G.camera*.24)%(SW+350))-120,h=90+(i%5)*49;rect(x,705-h,190,h,p.mid)}for(let i=0;i<11;i++){let x=120+i*520-G.camera*.72;if(x>-180&&x<SW+180)tree(x,L.gy-7,.78+(i%3)*.12,p)}if(L.spec.world>=5&&L.spec.world<=12){for(let i=0;i<3;i++){const x=700+i*1900-G.camera*.55;rect(x,390,62,340,'#1595e688');rect(x+14,390,12,340,'#9becff99')}}}
function platform(s,L){const p=pals[L.spec.env],x=s.x-G.camera,y=s.y;if(x+s.w<0||x>SW)return;let alpha=1;if(s.type==='ghost')alpha=s.visible?1:.17;ctx.globalAlpha=alpha;rect(x,y,s.w,s.h,p.dirt);for(let xx=x;xx<x+s.w;xx+=34){rect(xx,y,32,20,p.grass);rect(xx,y+20,32,13,p.grass2);if((xx/34|0)%2)rect(xx+7,y+38,6,7,p.dirt2)}for(let yy=y+56;yy<Math.min(SH,y+s.h);yy+=34)for(let xx=x;xx<x+s.w;xx+=34)if(((xx+yy)/34|0)%2)rect(xx+2,yy,30,30,p.dirt2);ctx.globalAlpha=1}
function coin(it){if(it.taken)return;const x=it.x-G.camera,y=it.y;ctx.fillStyle='#ffb000';ctx.beginPath();ctx.arc(x,y,16,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffe35a';ctx.beginPath();ctx.arc(x,y,11,0,Math.PI*2);ctx.fill();rect(x-3,y-10,6,20,'#fff2a2')}
function star(it){if(it.taken)return;const x=it.x-G.camera,y=it.y;ctx.save();ctx.translate(x,y);ctx.fillStyle='#ffd52d';ctx.beginPath();for(let i=0;i<10;i++){const r=i%2?11:22,a=-Math.PI/2+i*Math.PI/5;ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath();ctx.fill();ctx.strokeStyle='#8b5100';ctx.lineWidth=4;ctx.stroke();ctx.restore()}
function keyDraw(it){if(it.taken)return;const x=it.x-G.camera,y=it.y;rect(x-8,y-8,74,74,'#fff3aa22');rect(x+4,y+18,22,22,'#ffef9a');rect(x+8,y+22,14,14,'#7b5a00');rect(x+22,y+24,28,10,'#ffd54a');rect(x+40,y+24,8,18,'#ffd54a');rect(x+20,y,16,16,'#8be5ff');rect(x+24,y+4,8,8,'#dffbff')}
function bounce(it){const x=it.x-G.camera,y=it.y;rect(x,y,it.w,it.h,'#d98a00');rect(x+5,y-8,it.w-10,11,'#ffd43a');rect(x+16,y-14,it.w-32,7,'#fff0a0')}
function door(it){if(it.open)return;const x=it.x-G.camera,y=it.y;rect(x,y,it.w,it.h,'#275b86');rect(x+8,y+10,it.w-16,it.h-10,'#183c5e');rect(x+20,y+55,20,20,'#ffd43a')}
function portal(p,open){const x=p.x-G.camera,y=p.y;rect(x-14,y-14,p.w+28,p.h+14,'#4d5368');rect(x-8,y-8,p.w+16,p.h+8,'#8993a7');rect(x,y,p.w,p.h,open?'#53dfff':'#1a2c3e');if(open)for(let i=0;i<5;i++)rect(x+15+i*13,y+12+(i%2)*20,8,p.h-34,'#efffff88')}
function jumper(e){const x=e.x-G.camera,y=e.y;rect(x+5,y+5,44,42,'#77ce32');rect(x+11,y,32,12,'#8fe34b');rect(x,y+34,54,20,'#4fa820');rect(x+9,y+13,11,12,'#fff');rect(x+34,y+13,11,12,'#fff');rect(x+13,y+17,5,6,'#183421');rect(x+38,y+17,5,6,'#183421')}
function flyer(e){const x=e.x-G.camera,y=e.y;rect(x+10,y+10,45,28,'#1d83d2');rect(x+20,y+2,28,12,'#39a9ee');rect(x+47,y+14,17,10,'#ffb31c');rect(x-5,y+4,18,11,'#eaf8ff');rect(x+49,y+2,18,11,'#eaf8ff');rect(x+19,y+12,10,11,'#fff');rect(x+22,y+15,4,5,'#10253a')}
function bossDraw(b){const x=b.x-G.camera,y=b.y;rect(x+18,y+22,138,125,'#63b92f');rect(x,y+70,174,90,'#4e9e2a');rect(x+28,y+4,118,40,'#77cd3d');rect(x+30,y+50,31,31,'#fff');rect(x+113,y+50,31,31,'#fff');rect(x+40,y+59,11,12,'#183420');rect(x+123,y+59,11,12,'#183420');rect(x+48,y+112,80,14,'#2b6c29')}
function hero(p){const x=p.x-G.camera,y=p.y,c=[['#ff4ea0','#f4c59c','#ff5d7f','#3f87d6'],['#6b40ce','#f4c59c','#6840cf','#333f84'],['#18c4c6','#e4b180','#12b9c2','#2e8f8e'],['#7b451f','#f0c291','#167be0','#2d5f8a'],['#171717','#efb384','#c52b2c','#323844'],['#ff6412','#efc28b','#3b9c38','#40502f']][save.hero||0];rect(x+12,y+43,14,25,c[3]);rect(x+34,y+43,14,25,c[3]);rect(x+8,y+67,20,8,'#1b2735');rect(x+32,y+67,20,8,'#1b2735');rect(x+8,y+23,44,30,c[2]);rect(x,y+28,12,24,c[1]);rect(x+49,y+26,12,24,c[1]);rect(x+10,y+2,42,28,c[1]);rect(x+7,y,48,12,c[0]);rect(x+4,y+7,13,21,c[0]);rect(x+45,y+7,13,21,c[0]);rect(x+19,y+13,6,6,'#132033');rect(x+39,y+13,6,6,'#132033');rect(x+27,y+24,12,4,'#a34235')}
function wind(z){const x=z.x-G.camera;if(x+z.w<0||x>SW)return;ctx.globalAlpha=.35;for(let i=0;i<10;i++){const yy=150+i*55,xx=x+((performance.now()/8*(z.dir>0?1:-1)+i*103)%z.w);rect(xx,yy,70,6,'#e8fbff')}ctx.globalAlpha=1}
function render(){const L=G.L;background(L);L.zones.forEach(wind);L.plats.forEach(s=>platform(s,L));L.dyn.forEach(s=>platform(s,L));L.items.forEach(it=>{if(it.type==='coin')coin(it);else if(it.type==='star')star(it);else if(it.type==='key')keyDraw(it);else if(it.type==='bounce')bounce(it);else if(it.type==='door')door(it)});if(L.boss)L.boss.keys.forEach(keyDraw);L.enemies.forEach(e=>e.type==='jumper'?jumper(e):flyer(e));if(L.boss)bossDraw(L.boss);const open=(!L.boss||L.boss.keys.every(k=>k.taken))&&!L.items.some(x=>x.type==='door'&&!x.open);portal(L.portal,open);hero(G.p)}
function loop(t){if(!G||G.dead||G.finished)return;const dt=Math.min(.03,(t-last)/1000);last=t;if(!paused){update(dt);render()}requestAnimationFrame(loop)}
})();
